#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

vmware-user-suid-wrapper &

feh --bg-fill /etc/bgs/d9d7ad104360973.5f6142500e188.png
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1
~/.config/polybar/./launch.sh
picom &
bspc config border_width 0
